import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Addemployeeformframe extends javax.swing.JFrame {

    /**
     * Creates new form Addemployeeformframe
     */
    public Addemployeeformframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textcno = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textdesig = new javax.swing.JTextField();
        textsal = new javax.swing.JTextField();
        lblmessage = new javax.swing.JLabel();
        btadd = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        textqualify = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 750));
        setMinimumSize(new java.awt.Dimension(700, 750));

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("Fill Required Information !!!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("EMPLOYEE NAME *");
        jLabel2.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel2.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel2.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("MOBILE NO. *");
        jLabel3.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel3.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel3.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("EMAIL ID");
        jLabel4.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel4.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel4.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("DESIGNATION");
        jLabel5.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel5.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel5.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("SALARY *");
        jLabel6.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel6.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(235, 38));

        textname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textname.setMaximumSize(new java.awt.Dimension(235, 38));
        textname.setMinimumSize(new java.awt.Dimension(235, 38));
        textname.setPreferredSize(new java.awt.Dimension(235, 38));
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        textname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textnameKeyPressed(evt);
            }
        });

        textcno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textcno.setMaximumSize(new java.awt.Dimension(235, 38));
        textcno.setMinimumSize(new java.awt.Dimension(235, 38));
        textcno.setPreferredSize(new java.awt.Dimension(235, 38));
        textcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textcnoKeyPressed(evt);
            }
        });

        textemail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textemail.setMaximumSize(new java.awt.Dimension(235, 38));
        textemail.setMinimumSize(new java.awt.Dimension(235, 38));
        textemail.setPreferredSize(new java.awt.Dimension(235, 38));

        textdesig.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textdesig.setMaximumSize(new java.awt.Dimension(235, 38));
        textdesig.setMinimumSize(new java.awt.Dimension(235, 38));
        textdesig.setPreferredSize(new java.awt.Dimension(235, 38));

        textsal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textsal.setMaximumSize(new java.awt.Dimension(235, 38));
        textsal.setMinimumSize(new java.awt.Dimension(235, 38));
        textsal.setPreferredSize(new java.awt.Dimension(235, 38));
        textsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textsalKeyPressed(evt);
            }
        });

        lblmessage.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        btadd.setBackground(new java.awt.Color(0, 204, 102));
        btadd.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btadd.setText("HIRE");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btback.setBackground(new java.awt.Color(204, 0, 0));
        btback.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btclear.setBackground(new java.awt.Color(255, 255, 0));
        btclear.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        textqualify.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textqualify.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textqualifyKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("QUALIFICATION *");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("JOINING DATE (YYYY-MM-DD) *");

        textdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textdate.setMaximumSize(new java.awt.Dimension(235, 38));
        textdate.setMinimumSize(new java.awt.Dimension(235, 38));
        textdate.setPreferredSize(new java.awt.Dimension(235, 38));
        textdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textdateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textcno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textdesig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textqualify))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btclear, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(97, 97, 97)
                            .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textcno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textdesig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textqualify, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(lblmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btadd, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        try{
            Random r1=new Random();
            int a=r1.nextInt(1,9);
            int b=r1.nextInt(1,9);
            int c=r1.nextInt(1,9);
            int d=r1.nextInt(1,9);
	    String emp_id= "ISCEMP"+a+""+b+""+c+""+d;
            String emp_password= "emp"+c+""+d+""+"@@rh";
            String emp_name= textname.getText().trim();
            String ecno=textcno.getText().trim();
            String email=textemail.getText().trim();
            String desig = textdesig.getText().trim();
            String salary = textsal.getText().trim();
            String qualify =textqualify .getText().trim();
            String j_date = textdate.getText().trim();
            if (emp_name.isEmpty() || ecno.isEmpty() || salary.isEmpty() || qualify.isEmpty()|| j_date.isEmpty()) {
                lblmessage.setText("❌ Please fill all the mandatory fields.");
                return;
            }
            if (!j_date.matches("\\d{4}-\\d{2}-\\d{2}")) {
                lblmessage.setText("❌ Please enter date in YYYY-MM-DD format.");
                return;
            }
            if (!ecno.matches("\\d{10}")) {
            lblmessage.setText("❌ Invalid! Phone number must be 10 digits");
            return;   
}

            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="insert into employee(emp_id,emp_password,emp_name,ecno,desig,salary,qualify,j_date,email_id) values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps1= con.prepareStatement(qry);
	    ps1.setString(1,emp_id);
	    ps1.setString(2,emp_password);
	    ps1.setString(3,emp_name);
	    ps1.setString(4,ecno);
	    ps1.setString(5,desig);
	    ps1.setString(6,salary);
	    ps1.setString(7,qualify);
	    ps1.setString(8,j_date);
            ps1.setString(9,email);
            int a1=ps1.executeUpdate();
            if (a1==1){
                dispose();
                new Hireconfirmframe(emp_id,emp_password,"Employee").setVisible(true);
            }
            else{
                lblmessage.setText("ERROR!! Try Again");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        lblmessage.setText("");
        textcno.setText("");
        textdate.setText("");
        textdesig.setText("");
        textemail.setText("");
        textname.setText("");
        textqualify.setText("");
        textsal.setText("");
    }//GEN-LAST:event_btclearActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
         dispose();
         new Employeeblockhomeframe().setVisible(true);
                 
                 
    }//GEN-LAST:event_btbackActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void textnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnameKeyPressed
        lblmessage.setText("");
    }//GEN-LAST:event_textnameKeyPressed

    private void textcnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcnoKeyPressed
        lblmessage.setText("");
    }//GEN-LAST:event_textcnoKeyPressed

    private void textsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textsalKeyPressed
        lblmessage.setText("");
    }//GEN-LAST:event_textsalKeyPressed

    private void textqualifyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textqualifyKeyPressed
        lblmessage.setText("");
    }//GEN-LAST:event_textqualifyKeyPressed

    private void textdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textdateKeyPressed
        lblmessage.setText("");
    }//GEN-LAST:event_textdateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployeeformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addemployeeformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addemployeeformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addemployeeformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addemployeeformframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btback;
    private javax.swing.JButton btclear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmessage;
    private javax.swing.JTextField textcno;
    private javax.swing.JTextField textdate;
    private javax.swing.JTextField textdesig;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textqualify;
    private javax.swing.JTextField textsal;
    // End of variables declaration//GEN-END:variables
}
