
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Addservicepartnerformframe extends javax.swing.JFrame {
    String spap_type, spap_brand;
    /**
     * Creates new form Addservicepartnerformframe
     */
    public Addservicepartnerformframe() {
        initComponents();
        cmbapp.setVisible(false);
        cmbbrand.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textcno = new javax.swing.JTextField();
        lblmess = new javax.swing.JLabel();
        btadd = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        cmbtype = new javax.swing.JComboBox<>();
        cmbapp = new javax.swing.JComboBox<>();
        cmbbrand = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("Fill Required Information !!!!");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("PARTNER NAME *");
        jLabel2.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("MOBILE NO. *");
        jLabel3.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel3.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel3.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("SERVICE TYPE * ");
        jLabel4.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel4.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel4.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("APPLIANCE TYPE");
        jLabel5.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel5.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel5.setPreferredSize(new java.awt.Dimension(235, 38));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("APPLIANCE BRAND");
        jLabel6.setMaximumSize(new java.awt.Dimension(235, 38));
        jLabel6.setMinimumSize(new java.awt.Dimension(235, 38));
        jLabel6.setPreferredSize(new java.awt.Dimension(235, 38));

        textname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textnameKeyPressed(evt);
            }
        });

        textcno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textcnoKeyPressed(evt);
            }
        });

        lblmess.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        btadd.setBackground(new java.awt.Color(0, 204, 0));
        btadd.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btadd.setText("ADD");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btclear.setBackground(new java.awt.Color(255, 255, 0));
        btclear.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        btback.setBackground(new java.awt.Color(204, 0, 0));
        btback.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        cmbtype.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SERVICE TYPE", "Electrician", "Plumber", "Appliance Care", "Painter", "Carpenter" }));
        cmbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtypeActionPerformed(evt);
            }
        });

        cmbapp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbapp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPLIANCE", "Air Conditioner", "Home Theatre", "Microwave/Oven", "Refrigerator", "Smart TV", "Washing Machine" }));
        cmbapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbappActionPerformed(evt);
            }
        });

        cmbbrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbbrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRAND", "LG", "Panasonic", "Hitachi", "Goderej", "Xiaomi", "Samsung", "Daikin", "Havels", "Sony", "Philips", "Multi" }));
        cmbbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textname, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(textcno)
                                    .addComponent(cmbtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbapp, 0, 304, Short.MAX_VALUE)
                                    .addComponent(cmbbrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblmess, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbtype))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbapp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbbrand))
                .addGap(42, 42, 42)
                .addComponent(lblmess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btadd)
                .addGap(18, 18, 18)
                .addComponent(btclear)
                .addGap(18, 18, 18)
                .addComponent(btback)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        try{
            Random r1=new Random();
            int a=r1.nextInt(1,9);
            int b=r1.nextInt(1,9);
            int c=r1.nextInt(1,9);
            int d=r1.nextInt(1,9);
	    String sp_id= "ISCSP"+a+""+b+""+c+""+d;
            String sp_pass= "";
            String sp_name= textname.getText().trim();
            String sp_cno=textcno.getText().trim();
            
            String sp_type=cmbtype.getSelectedItem().toString().trim();;
            int vs_charge=0;
            if(sp_type.equalsIgnoreCase("Electrician")){
                sp_pass= "spar"+c+""+d+""+"@@el";
                vs_charge=100;
            }
            if(sp_type.equalsIgnoreCase("Plumber")){
                sp_pass= "spar"+c+""+d+""+"@@pl";
                vs_charge=100;
            }
            if(sp_type.equalsIgnoreCase("Appliance Care")){
                sp_pass= "spar"+c+""+d+""+"@@ap";
                vs_charge=250;
                spap_type = cmbapp.getSelectedItem().toString().trim();
                spap_brand = cmbbrand.getSelectedItem().toString().trim();
            }
            if(sp_type.equalsIgnoreCase("Painter")){
                sp_pass= "spar"+c+""+d+""+"@@pt";
                vs_charge=300;
            }
            if(sp_type.equalsIgnoreCase("Carpenter")){
                sp_pass= "spar"+c+""+d+""+"@@cp";
                vs_charge=100;
            }
            if(sp_type.equalsIgnoreCase("SERVICE TYPE")){
                lblmess.setText("Select Partner Type"); 
                return;
            }
            if (sp_name.isEmpty() || sp_cno.isEmpty()) {
                lblmess.setText("❌ Please fill all the mandatory fields.");
                return;
            }
            
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="insert into partner(sp_id,sp_pass,sp_name,sp_cno,sp_type,spap_type,spap_brand,sp_status,tp_pending,vs_charge) values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps1= con.prepareStatement(qry);
	    ps1.setString(1,sp_id);
	    ps1.setString(2,sp_pass);
	    ps1.setString(3,sp_name);
	    ps1.setString(4,sp_cno);
	    ps1.setString(5,sp_type);
	    ps1.setString(6,spap_type);
	    ps1.setString(7,spap_brand);
	    ps1.setString(8,"Active");
            ps1.setInt(9,0);
            ps1.setInt(10,vs_charge);
            int a1=ps1.executeUpdate();
            if (a1==1){
                dispose();
                new Hireconfirmframe(sp_id,sp_pass,"Partner").setVisible(true);
            }
            else{
                lblmess.setText("ERROR!! Try Again");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
             
    }//GEN-LAST:event_btaddActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        textname.setText("");
        textcno.setText("");
        cmbapp.setSelectedIndex(0);
        cmbbrand.setSelectedIndex(0);
        cmbtype.setSelectedIndex(0);
        lblmess.setText("");
        cmbapp.setVisible(false);
        cmbbrand.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_btclearActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        new Spblockhomeframe().setVisible(true);
    }//GEN-LAST:event_btbackActionPerformed

    private void textnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnameKeyPressed
        lblmess.setText("");
    }//GEN-LAST:event_textnameKeyPressed

    private void textcnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textcnoKeyPressed
        lblmess.setText("");
    }//GEN-LAST:event_textcnoKeyPressed

    private void cmbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtypeActionPerformed
        lblmess.setText("");
        String sp_type=cmbtype.getSelectedItem().toString().trim();
        boolean isAppliance = sp_type.equals("Appliance Care");
            cmbapp.setVisible(isAppliance);
            cmbbrand.setVisible(isAppliance);
            jLabel5.setVisible(isAppliance);
            jLabel6.setVisible(isAppliance);
    }//GEN-LAST:event_cmbtypeActionPerformed

    private void cmbappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbappActionPerformed
        lblmess.setText("");
    }//GEN-LAST:event_cmbappActionPerformed

    private void cmbbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbrandActionPerformed
        lblmess.setText("");
    }//GEN-LAST:event_cmbbrandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addservicepartnerformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addservicepartnerformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addservicepartnerformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addservicepartnerformframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addservicepartnerformframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btback;
    private javax.swing.JButton btclear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbapp;
    private javax.swing.JComboBox<String> cmbbrand;
    private javax.swing.JComboBox<String> cmbtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmess;
    private javax.swing.JTextField textcno;
    private javax.swing.JTextField textname;
    // End of variables declaration//GEN-END:variables
}
