
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Filterpartnerinputframe extends javax.swing.JFrame {

    /**
     * Creates new form Filterpartnerinputframe
     */
    public Filterpartnerinputframe() {
        initComponents();
        comboappliance.setVisible(false);
        combobrand.setVisible(false);
        lblappliance.setVisible(false);
        lblbrand.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        combotask = new javax.swing.JComboBox<>();
        lblservice = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        combostatus = new javax.swing.JComboBox<>();
        lbltask = new javax.swing.JLabel();
        comboservice = new javax.swing.JComboBox<>();
        lblappliance = new javax.swing.JLabel();
        comboappliance = new javax.swing.JComboBox<>();
        lblbrand = new javax.swing.JLabel();
        combobrand = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblmess = new javax.swing.JLabel();
        btsearch = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        btback = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 750));
        setMinimumSize(new java.awt.Dimension(700, 750));

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        combotask.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        combotask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TASK PENDING", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combotask.setMaximumSize(new java.awt.Dimension(264, 32));
        combotask.setMinimumSize(new java.awt.Dimension(264, 32));
        combotask.setPreferredSize(new java.awt.Dimension(264, 32));
        combotask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotaskActionPerformed(evt);
            }
        });

        lblservice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblservice.setText("Service Type");

        lblstatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblstatus.setText("Partner Status");

        combostatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        combostatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STATUS", "Active", "Avavilable", "Busy", "On Leave", "Working", "Assigned" }));
        combostatus.setMaximumSize(new java.awt.Dimension(264, 32));
        combostatus.setMinimumSize(new java.awt.Dimension(264, 32));
        combostatus.setPreferredSize(new java.awt.Dimension(264, 32));
        combostatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combostatusActionPerformed(evt);
            }
        });

        lbltask.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltask.setText("Task Pending Count");

        comboservice.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboservice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SERVICE TYPE", "Electrician", "Plumber", "Appliance Care", "Painter", "Carpenter" }));
        comboservice.setMaximumSize(new java.awt.Dimension(264, 32));
        comboservice.setMinimumSize(new java.awt.Dimension(264, 32));
        comboservice.setPreferredSize(new java.awt.Dimension(264, 32));
        comboservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboserviceActionPerformed(evt);
            }
        });

        lblappliance.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblappliance.setText("Appliance Type");

        comboappliance.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comboappliance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPLIANCE", "Air Conditioner", "Home Theatre", "Microwave/Oven", "Refrigerator", "Smart TV", "Washing Machine" }));
        comboappliance.setMaximumSize(new java.awt.Dimension(264, 32));
        comboappliance.setMinimumSize(new java.awt.Dimension(264, 32));
        comboappliance.setPreferredSize(new java.awt.Dimension(264, 32));
        comboappliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboapplianceActionPerformed(evt);
            }
        });

        lblbrand.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblbrand.setText("Appliance Brand");

        combobrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        combobrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BRAND", "LG", "Panasonic", "Hitachi", "Goderej", "Xiaomi", "Samsung", "Daikin", "Havels", "Sony", "Philips" }));
        combobrand.setMaximumSize(new java.awt.Dimension(264, 32));
        combobrand.setMinimumSize(new java.awt.Dimension(264, 32));
        combobrand.setPreferredSize(new java.awt.Dimension(264, 32));
        combobrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobrandActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel6.setText("FILTER SERVICE PARTNER !!!!");

        lblmess.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        btsearch.setBackground(new java.awt.Color(0, 204, 0));
        btsearch.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btsearch.setText("SEARCH");
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });

        btclear.setBackground(new java.awt.Color(255, 255, 0));
        btclear.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        btback.setBackground(new java.awt.Color(204, 0, 0));
        btback.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblmess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblappliance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblservice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(lblstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combostatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combotask, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboservice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboappliance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combobrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combostatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltask, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combotask, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblservice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboservice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblappliance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboappliance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(lblmess, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btsearch)
                .addGap(18, 18, 18)
                .addComponent(btclear)
                .addGap(18, 18, 18)
                .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboapplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboapplianceActionPerformed
        lblmess.setText("");
    }//GEN-LAST:event_comboapplianceActionPerformed

    private void comboserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboserviceActionPerformed
        lblmess.setText("");
        String selected=comboservice.getSelectedItem().toString();
        boolean isAppliance = selected.equals("Appliance Care");
        comboappliance.setVisible(isAppliance);
        combobrand.setVisible(isAppliance);
        lblappliance.setVisible(isAppliance);
        lblbrand.setVisible(isAppliance);
    }//GEN-LAST:event_comboserviceActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        String qry= "Select * from partner where 1=1";
        ArrayList<String> filters= new ArrayList<>();
        String type = comboservice.getSelectedItem().toString();
        String status = combostatus.getSelectedItem().toString();
        String task = combotask.getSelectedItem().toString();
        String appType = comboappliance.getSelectedItem().toString();
        String brand = combobrand.getSelectedItem().toString();
        boolean filterApplied = false;
        System.out.println("Final Query: " + qry);
        System.out.println("Filters: " + filters);

        if(!type.equals("SERVICE TYPE")){
            qry+=" and sp_type=?";
            filters.add(type);
            filterApplied= true;
            lblmess.setText("");
            if(type.equals("Appliance Care")){
                if(!appType.equals("APPLIANCE")){
                    qry += " and spap_type = ?";
                    filters.add(appType);  
                }
                 if (!brand.equals("BRAND")) {
                    qry += " and spap_brand = ?";
                    filters.add(brand);
                }
                 
            }
        }
        if (!status.equals("STATUS")) {
        qry += " and sp_status = ?";
        filters.add(status);
        filterApplied = true;
        lblmess.setText("");
        }

        if (!task.equals("TASK PENDING")) {
            qry += " and tp_pending = ?";
            filters.add(task);
            filterApplied = true;
            lblmess.setText("");
        }
        if(filterApplied == false){
            lblmess.setText("Please select at least one Filter");
            return;
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
                PreparedStatement ps = con.prepareStatement(qry);
            for (int i = 0; i < filters.size(); i++) {
                ps.setString(i + 1, filters.get(i));
            }
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                
                new Filterpartnerresultframe(qry, filters).setVisible(true);
                this.dispose();
            } else {
                lblmess.setText("No record found.");
            }
        } catch (Exception e) {
            System.out.println(e);
            lblmess.setText("Error occurred.");
        }

    }//GEN-LAST:event_btsearchActionPerformed

    private void combostatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combostatusActionPerformed
        lblmess.setText("");
    }//GEN-LAST:event_combostatusActionPerformed

    private void combotaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotaskActionPerformed
        lblmess.setText("");
    }//GEN-LAST:event_combotaskActionPerformed

    private void combobrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobrandActionPerformed
        lblmess.setText("");
    }//GEN-LAST:event_combobrandActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        new Spblockhomeframe().setVisible(true);
    }//GEN-LAST:event_btbackActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        combostatus.setSelectedIndex(0);
        combotask.setSelectedIndex(0);
        comboservice.setSelectedIndex(0);
        comboappliance.setSelectedIndex(0);
        combobrand.setSelectedIndex(0);
        comboappliance.setVisible(false);
        combobrand.setVisible(false);
        lblappliance.setVisible(false);
        lblbrand.setVisible(false);
        lblmess.setText("");
       
       
    }//GEN-LAST:event_btclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filterpartnerinputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filterpartnerinputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filterpartnerinputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filterpartnerinputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filterpartnerinputframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btsearch;
    private javax.swing.JComboBox<String> comboappliance;
    private javax.swing.JComboBox<String> combobrand;
    private javax.swing.JComboBox<String> comboservice;
    private javax.swing.JComboBox<String> combostatus;
    private javax.swing.JComboBox<String> combotask;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblappliance;
    private javax.swing.JLabel lblbrand;
    private javax.swing.JLabel lblmess;
    private javax.swing.JLabel lblservice;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lbltask;
    // End of variables declaration//GEN-END:variables
}
