
import java.awt.Color;
import javax.swing.border.MatteBorder;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Homeframe extends javax.swing.JFrame {

    /**
     * Creates new form Homeframe
     */
    public Homeframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbwel = new javax.swing.JLabel();
        btuser = new javax.swing.JButton();
        btcom = new javax.swing.JButton();
        btadmin = new javax.swing.JButton();
        btsp = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        lblcom = new javax.swing.JLabel();
        lbladmin = new javax.swing.JLabel();
        lbsp = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        lbwel.setBackground(new java.awt.Color(255, 228, 184));
        lbwel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
        lbwel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbwel.setText("WELCOME");
        lbwel.setBorder(new javax.swing.border.MatteBorder(null));
        lbwel.setOpaque(true);

        btuser.setBackground(new java.awt.Color(153, 153, 153));
        btuser.setIcon(new javax.swing.ImageIcon("F:\\SATYAM JAIN\\javaprog\\HomeSupport\\src\\images\\resized_user_icon_200x200.png")); // NOI18N
        btuser.setPreferredSize(new java.awt.Dimension(200, 200));
        btuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btuserActionPerformed(evt);
            }
        });

        btcom.setBackground(new java.awt.Color(0, 51, 153));
        btcom.setIcon(new javax.swing.ImageIcon("F:\\SATYAM JAIN\\javaprog\\HomeSupport\\src\\images\\Buildings and Gear Icon.png")); // NOI18N
        btcom.setMaximumSize(new java.awt.Dimension(200, 200));
        btcom.setMinimumSize(new java.awt.Dimension(200, 200));
        btcom.setPreferredSize(new java.awt.Dimension(200, 200));
        btcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcomActionPerformed(evt);
            }
        });

        btadmin.setBackground(new java.awt.Color(0, 0, 0));
        btadmin.setIcon(new javax.swing.ImageIcon("F:\\SATYAM JAIN\\javaprog\\HomeSupport\\src\\images\\icon_200x200.png")); // NOI18N
        btadmin.setPreferredSize(new java.awt.Dimension(200, 200));
        btadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadminActionPerformed(evt);
            }
        });

        btsp.setBackground(new java.awt.Color(0, 153, 153));
        btsp.setIcon(new javax.swing.ImageIcon("F:\\SATYAM JAIN\\javaprog\\HomeSupport\\src\\images\\resized_200x200.png")); // NOI18N
        btsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btspActionPerformed(evt);
            }
        });

        lbluser.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbluser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbluser.setText("USER PANEL");

        lblcom.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblcom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcom.setText("COMPANY PANEL");
        lblcom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbladmin.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbladmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladmin.setText("ADMIN PANEL");
        lbladmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbsp.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbsp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbsp.setText("PARTNER PANEL");

        btexit.setBackground(new java.awt.Color(153, 0, 0));
        btexit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btexit.setText("EXIT");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbwel, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbladmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btadmin, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(btuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btcom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(btexit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbwel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btcom, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(btuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluser)
                    .addComponent(lblcom))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladmin)
                    .addComponent(lbsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btexit)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btuserActionPerformed
        dispose();
        new Userframehome().setVisible(true);
    }//GEN-LAST:event_btuserActionPerformed

    private void btcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcomActionPerformed
        dispose();
        new Companyloginpageframe().setVisible(true);
    }//GEN-LAST:event_btcomActionPerformed

    private void btadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadminActionPerformed
        dispose();
        new Adminloginpageframe().setVisible(true);
        
    }//GEN-LAST:event_btadminActionPerformed

    private void btspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btspActionPerformed
        dispose();
        new Underdevelopmentframe().setVisible(true);
    }//GEN-LAST:event_btspActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homeframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadmin;
    private javax.swing.JButton btcom;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btsp;
    private javax.swing.JButton btuser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JLabel lblcom;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbsp;
    private javax.swing.JLabel lbwel;
    // End of variables declaration//GEN-END:variables
}
