
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Removepartnerdetailframe extends javax.swing.JFrame {
    String sp_id,name,contact,type,fullText,fullcno,fulltype;
    /**
     * Creates new form Removepartnerdetailframe
     */
    public Removepartnerdetailframe(String sp_id) {
        initComponents();
        this.sp_id=sp_id;
        fetchPartnerDetails();
    }
    private void fetchPartnerDetails(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="Select sp_id,sp_name,sp_cno,sp_type,spap_type,spap_brand,sp_status,tp_pending,vs_charge from partner where sp_id=?";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,sp_id);
            ResultSet rs=ps.executeQuery();
            if (rs.next()){
                textid.setText("Service Partner Id: " + rs.getString("sp_id"));
                textname.setText("Partner Name: " + rs.getString("sp_name"));
                textcno.setText("Phone: " + rs.getString("sp_cno"));
                texttype.setText("Service Type: " + rs.getString("sp_type"));
                textapp.setText("Appliance Type: " + rs.getString("spap_type"));
                textbrand.setText("Appliance Brand: " + rs.getString("spap_brand"));
                textstatus.setText("Status: " + rs.getString("sp_status"));
                textpend.setText("Task Pending: " + rs.getString("tp_pending"));
                textvs.setText("Visiting Charges: "+ rs.getString("vs_charge"));
            }
            else{
               lblmess.setText("Unable to fetch records");
            }
            fullText = textname.getText(); 
            fullcno=textcno.getText();
            fulltype=texttype.getText();
            name = fullText.substring(fullText.indexOf(":") + 2);
            contact = fullcno.substring(fullcno.indexOf(":") + 2);
            type=fulltype.substring(fulltype.indexOf(":") + 2);
            
        }
        catch(Exception e){
            System.out.println(e);       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textid = new javax.swing.JLabel();
        textname = new javax.swing.JLabel();
        textcno = new javax.swing.JLabel();
        texttype = new javax.swing.JLabel();
        textapp = new javax.swing.JLabel();
        textbrand = new javax.swing.JLabel();
        textstatus = new javax.swing.JLabel();
        textpend = new javax.swing.JLabel();
        textvs = new javax.swing.JLabel();
        btfire = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        lblmess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 750));
        setMinimumSize(new java.awt.Dimension(700, 750));

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Details are......");

        textid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textid.setMaximumSize(new java.awt.Dimension(565, 38));
        textid.setMinimumSize(new java.awt.Dimension(565, 38));
        textid.setPreferredSize(new java.awt.Dimension(565, 38));

        textname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textname.setMaximumSize(new java.awt.Dimension(565, 38));
        textname.setMinimumSize(new java.awt.Dimension(565, 38));
        textname.setPreferredSize(new java.awt.Dimension(565, 38));

        textcno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textcno.setToolTipText("");
        textcno.setMaximumSize(new java.awt.Dimension(565, 38));
        textcno.setMinimumSize(new java.awt.Dimension(565, 38));
        textcno.setPreferredSize(new java.awt.Dimension(565, 38));

        texttype.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texttype.setMaximumSize(new java.awt.Dimension(565, 38));
        texttype.setMinimumSize(new java.awt.Dimension(565, 38));
        texttype.setPreferredSize(new java.awt.Dimension(565, 38));

        textapp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textapp.setMaximumSize(new java.awt.Dimension(565, 38));
        textapp.setMinimumSize(new java.awt.Dimension(565, 38));
        textapp.setPreferredSize(new java.awt.Dimension(565, 38));

        textbrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textbrand.setMaximumSize(new java.awt.Dimension(565, 38));
        textbrand.setMinimumSize(new java.awt.Dimension(565, 38));
        textbrand.setPreferredSize(new java.awt.Dimension(565, 38));

        textstatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textstatus.setToolTipText("");
        textstatus.setMaximumSize(new java.awt.Dimension(565, 38));
        textstatus.setMinimumSize(new java.awt.Dimension(565, 38));
        textstatus.setPreferredSize(new java.awt.Dimension(565, 38));

        textpend.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textpend.setMaximumSize(new java.awt.Dimension(565, 38));
        textpend.setMinimumSize(new java.awt.Dimension(565, 38));
        textpend.setPreferredSize(new java.awt.Dimension(565, 38));

        textvs.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textvs.setMaximumSize(new java.awt.Dimension(565, 38));
        textvs.setMinimumSize(new java.awt.Dimension(565, 38));
        textvs.setPreferredSize(new java.awt.Dimension(565, 38));

        btfire.setBackground(new java.awt.Color(204, 0, 0));
        btfire.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btfire.setText("FIRE");
        btfire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfireActionPerformed(evt);
            }
        });

        btback.setBackground(new java.awt.Color(0, 204, 0));
        btback.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        lblmess.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btfire, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(textname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textcno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(texttype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textbrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textpend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textcno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(texttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textpend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(textvs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblmess, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btfire, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btfireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfireActionPerformed
        dispose();
        new Removeconfirmationframe(sp_id,name,contact,"Service Partner",type).setVisible(true);
    }//GEN-LAST:event_btfireActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        new Removepartnerinputframe().setVisible(true);
    }//GEN-LAST:event_btbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Removepartnerdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Removepartnerdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Removepartnerdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Removepartnerdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btfire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmess;
    private javax.swing.JLabel textapp;
    private javax.swing.JLabel textbrand;
    private javax.swing.JLabel textcno;
    private javax.swing.JLabel textid;
    private javax.swing.JLabel textname;
    private javax.swing.JLabel textpend;
    private javax.swing.JLabel textstatus;
    private javax.swing.JLabel texttype;
    private javax.swing.JLabel textvs;
    // End of variables declaration//GEN-END:variables
}
