
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Searchempspdetailframe extends javax.swing.JFrame {
    String id;
    String mode;
    /**
     * Creates new form Searchemployeedetailframe
     */
    public Searchempspdetailframe(String mode,String id) {
        initComponents();
        this.id=id;
        this.mode=mode;
        fetchEmployeeDetails();
        
    }
    private void fetchEmployeeDetails(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            if(mode.equals("employee")){
                String qry="Select emp_id,emp_name,ecno,desig,salary,qualify,j_date,email_id,status from employee where emp_id=?";
                PreparedStatement ps=con.prepareStatement(qry);

                ps.setString(1,id);
                ResultSet rs=ps.executeQuery();
                if (rs.next()){
                    lblempid.setText("Employee Id: " + rs.getString("emp_id"));
                    lblname.setText("Employee Name: " + rs.getString("emp_name"));
                    lblcno.setText("Phone: " + rs.getString("ecno"));
                    lblemail.setText("Email: " + rs.getString("email_id"));
                    lbldesig.setText("Designation: " + rs.getString("desig"));
                    lblsal.setText("Salary: " + rs.getString("salary"));
                    lblqualify.setText("Qualification: " + rs.getString("qualify"));
                    lbldate.setText("Joining  Date: " + rs.getString("j_date"));
                    lblstatus.setText("Status: "+ rs.getString("status"));

                }
                else{
                   lblmess.setText("Unable to fetch records");
                }
            }
            else if(mode.equals("partner")){
                String qry="Select sp_id,sp_name,sp_cno,sp_type,spap_type,spap_brand,sp_status,tp_pending from partner where sp_id=?";
                PreparedStatement ps=con.prepareStatement(qry);
                ps.setString(1,id);
                ResultSet rs=ps.executeQuery();
                if (rs.next()){
                    lblempid.setText("Service Partner Id: " + rs.getString("sp_id"));
                    lblname.setText("Service Partner Name: " + rs.getString("sp_name"));
                    lblcno.setText("Phone: " + rs.getString("sp_cno"));
                    lblemail.setText("Service Type: " + rs.getString("sp_type"));
                    lbldesig.setText("Appliance Type: " + rs.getString("spap_type"));
                    lblsal.setText("Applaince Brand: " + rs.getString("spap_brand"));
                    lblqualify.setText("Partner Status: " + rs.getString("sp_status"));
                    lbldate.setText("Pending Task: " + rs.getString("tp_pending"));

                }
                else{
                   lblmess.setText("Unable to fetch records");
                }
            }
            if(mode.equals("admin")){
                String qry="Select adm_id,adm_name,acno,desig,salary,qualify,status,j_date from admin where adm_id=?";
                PreparedStatement ps=con.prepareStatement(qry);

                ps.setString(1,id);
                ResultSet rs=ps.executeQuery();
                if (rs.next()){
                    lblempid.setText("Admin Id: " + rs.getString("adm_id"));
                    lblname.setText("Admin Name: " + rs.getString("adm_name"));
                    lblcno.setText("Phone: " + rs.getString("acno"));
                    
                    
                    lblemail.setText("Designation: " + rs.getString("desig"));
                    lbldesig.setText("Salary: " + rs.getString("salary"));
                    lblsal.setText("Qualification: " + rs.getString("qualify"));
                    lblqualify.setText("Joining  Date: " + rs.getString("j_date"));
                    lbldate.setText("Status: "+ rs.getString("status"));

                }
                else{
                   lblmess.setText("Unable to fetch records");
                }
            }
        }
        catch(Exception e){
            System.out.println(e);       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblempid = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcno = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lbldesig = new javax.swing.JLabel();
        lblsal = new javax.swing.JLabel();
        lblqualify = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblmess = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Details are.......");

        lblempid.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblempid.setMaximumSize(new java.awt.Dimension(565, 28));
        lblempid.setMinimumSize(new java.awt.Dimension(565, 28));
        lblempid.setPreferredSize(new java.awt.Dimension(565, 28));

        lblname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblname.setMaximumSize(new java.awt.Dimension(565, 38));
        lblname.setMinimumSize(new java.awt.Dimension(565, 38));
        lblname.setPreferredSize(new java.awt.Dimension(565, 28));

        lblcno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblcno.setMaximumSize(new java.awt.Dimension(565, 38));
        lblcno.setMinimumSize(new java.awt.Dimension(565, 38));
        lblcno.setPreferredSize(new java.awt.Dimension(565, 28));

        lblemail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblemail.setMaximumSize(new java.awt.Dimension(565, 38));
        lblemail.setMinimumSize(new java.awt.Dimension(565, 38));
        lblemail.setPreferredSize(new java.awt.Dimension(565, 28));

        lbldesig.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbldesig.setMaximumSize(new java.awt.Dimension(565, 28));
        lbldesig.setMinimumSize(new java.awt.Dimension(565, 28));
        lbldesig.setPreferredSize(new java.awt.Dimension(565, 28));

        lblsal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblsal.setMaximumSize(new java.awt.Dimension(565, 38));
        lblsal.setMinimumSize(new java.awt.Dimension(565, 38));
        lblsal.setPreferredSize(new java.awt.Dimension(565, 28));

        lblqualify.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblqualify.setMaximumSize(new java.awt.Dimension(565, 38));
        lblqualify.setMinimumSize(new java.awt.Dimension(565, 38));
        lblqualify.setPreferredSize(new java.awt.Dimension(565, 28));

        lbldate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbldate.setMaximumSize(new java.awt.Dimension(565, 38));
        lbldate.setMinimumSize(new java.awt.Dimension(565, 38));
        lbldate.setPreferredSize(new java.awt.Dimension(565, 28));

        lblmess.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblmess.setPreferredSize(new java.awt.Dimension(565, 28));

        btback.setBackground(new java.awt.Color(255, 255, 51));
        btback.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        lblstatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblstatus.setPreferredSize(new java.awt.Dimension(565, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblempid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblcno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldesig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblqualify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblmess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(215, 215, 215))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(lblempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblcno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbldesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblqualify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(lblmess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        if(mode.equals("employee")) 
            new Employeeblockhomeframe().setVisible(true);
        else if(mode.equals("partner"))
            new Spblockhomeframe().setVisible(true);
        else if(mode.equals("admin"))
            new Adminheadhomeframe().setVisible(true);
    }//GEN-LAST:event_btbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchempspdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchempspdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchempspdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchempspdetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcno;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldesig;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblempid;
    private javax.swing.JLabel lblmess;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblqualify;
    private javax.swing.JLabel lblsal;
    private javax.swing.JLabel lblstatus;
    // End of variables declaration//GEN-END:variables
}
