
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Updatedetailframe extends javax.swing.JFrame {
    String r_id;
    /**
     * Creates new form updatedetailframe
     */
    public Updatedetailframe(String r_id) {
        initComponents();
        this.r_id=r_id;
        fetchRequestDetails();
    }
    private void fetchRequestDetails(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="Select * from status where r_id=?";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,r_id);
            ResultSet rs=ps.executeQuery();
            if (rs.next()){
                lbr_id.setText("Requst Id:" + " "+rs.getString("r_id"));
                lbcname.setText("Name:" +"  "+rs.getString("c_name"));
                lbcno.setText("Contact:" +"  "+rs.getString("cno"));
                lbstype.setText("Service Type:" +"  "+rs.getString("s_type"));
                lbrdate.setText("Requst Date:" +"  "+rs.getString("r_date"));
                lbstatus.setText("Status:" +"  "+rs.getString("status"));
                lbspid.setText("Service Partner Id:" +"  "+rs.getString("sp_id"));
                lbupdate.setText("Updation Date:" +"  "+rs.getString("up_date"));
                lbappl.setText("Appliance Type:" +"  "+rs.getString("appl_type"));
                lbbrand.setText("Appliance Brand:" +"  "+rs.getString("brand"));
            }
            else{
                lbr_id.setText("FAILED TO FETCH RECORDS");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbr_id = new javax.swing.JLabel();
        lbcname = new javax.swing.JLabel();
        lbcno = new javax.swing.JLabel();
        lbstype = new javax.swing.JLabel();
        lbrdate = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();
        lbspid = new javax.swing.JLabel();
        lbupdate = new javax.swing.JLabel();
        lbappl = new javax.swing.JLabel();
        lbbrand = new javax.swing.JLabel();
        btreject = new javax.swing.JButton();
        lbdate = new javax.swing.JLabel();
        textdate = new javax.swing.JTextField();
        btapprove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 750));

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Details are.....");

        lbr_id.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbcname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbcno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbstype.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbrdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbstatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbspid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbupdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbappl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbbrand.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btreject.setBackground(new java.awt.Color(204, 0, 0));
        btreject.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btreject.setText("REJECT");
        btreject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrejectActionPerformed(evt);
            }
        });

        lbdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbdate.setText("Enter Date (YYYY-MM-DD)");

        textdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btapprove.setBackground(new java.awt.Color(0, 204, 0));
        btapprove.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btapprove.setText("APPROVE");
        btapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btapproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(textdate, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btreject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btapprove))
                    .addComponent(lbstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbrdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbcname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbcno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbstype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbspid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbappl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbbrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbr_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbr_id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbcname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbcno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbstype, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbrdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbspid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbappl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textdate, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lbdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btapprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btreject, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrejectActionPerformed
        String update=textdate.getText().trim();
        if(update.isEmpty()){
            textdate.setText("Fill this");
        }
        if (!update.matches("\\d{4}-\\d{2}-\\d{2}")) {
                textdate.setText("YYYY-MM-DD format.");
                return;
            }
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="update status set status=? where r_id=?";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,"Rejected");
            ps.setString(2,r_id);
            int a=ps.executeUpdate();
            String qry1="update status set up_date=? where r_id=?";
            PreparedStatement ps1=con.prepareStatement(qry1);
            ps1.setString(1,update);
            ps1.setString(2,r_id);
            int a1=ps1.executeUpdate();
            if(a==1 && a1==1){
               dispose();
               new Updateconfirmframe().setVisible(true);
            }
            else{
               dispose();
               new Oopsframe().setVisible(true);
            }
            
         }
         catch(Exception e){
             System.out.println(e);         
         }
    }//GEN-LAST:event_btrejectActionPerformed

    private void btapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btapproveActionPerformed
        String update=textdate.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="update status set status=? where r_id=?";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,"Approved");
            ps.setString(2,r_id);
            int a=ps.executeUpdate();
            String qry1="update status set up_date=? where r_id=?";
            PreparedStatement ps1=con.prepareStatement(qry1);
            ps1.setString(1,update);
            ps1.setString(2,r_id);
            int a1=ps1.executeUpdate();
            if(a==1 && a1==1){
               dispose();
               new Updateconfirmframe().setVisible(true);
            }
            else{
               dispose();
               new Oopsframe().setVisible(true);
            }
            
         }
         catch(Exception e){
             System.out.println(e);         
         }
    }//GEN-LAST:event_btapproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updatedetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updatedetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updatedetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatedetailframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btapprove;
    private javax.swing.JButton btreject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbappl;
    private javax.swing.JLabel lbbrand;
    private javax.swing.JLabel lbcname;
    private javax.swing.JLabel lbcno;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbr_id;
    private javax.swing.JLabel lbrdate;
    private javax.swing.JLabel lbspid;
    private javax.swing.JLabel lbstatus;
    private javax.swing.JLabel lbstype;
    private javax.swing.JLabel lbupdate;
    private javax.swing.JTextField textdate;
    // End of variables declaration//GEN-END:variables
}
