
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Updateadminframe extends javax.swing.JFrame {
     boolean edit=false;
     String editname,editcno,editdesig,editqualify,mem_id;
     String fullname,fullcno,fulldesig,fullqualify;
    /**
     * Creates new form Updateadminframe
     */
    public Updateadminframe() {
        initComponents();
        lblname.setVisible(false);
        lblcno.setVisible(false);
        lbldesig.setVisible(false);
        lblqualify.setVisible(false);
        textnameedit.setVisible(false);
        textcnoedit.setVisible(false);
        textdesigedit.setVisible(false);
        textqualifyedit.setVisible(false);
        textadmid.setVisible(false);
        textpass.setVisible(false);
        edit1.setVisible(false);
        edit2.setVisible(false);
        edit3.setVisible(false);
        edit4.setVisible(false);
        btupdate.setVisible(false);
        lblid.setVisible(false);
        lblpass.setVisible(false);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textmemid = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        edit1 = new javax.swing.JButton();
        textnameedit = new javax.swing.JTextField();
        lblcno = new javax.swing.JLabel();
        edit2 = new javax.swing.JButton();
        textcnoedit = new javax.swing.JTextField();
        lbldesig = new javax.swing.JLabel();
        edit3 = new javax.swing.JButton();
        textdesigedit = new javax.swing.JTextField();
        lblqualify = new javax.swing.JLabel();
        edit4 = new javax.swing.JButton();
        textqualifyedit = new javax.swing.JTextField();
        btcheck = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        textadmid = new javax.swing.JTextField();
        lblpass = new javax.swing.JLabel();
        textpass = new javax.swing.JTextField();
        btupdate = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        btback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("Updatde Details>>>>");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Enter Member Admin Id ");

        textmemid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textmemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textmemidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textmemidKeyTyped(evt);
            }
        });

        lblname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblname.setPreferredSize(new java.awt.Dimension(0, 21));

        edit1.setBackground(new java.awt.Color(51, 204, 0));
        edit1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        edit1.setText("EDIT");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });

        textnameedit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textnameedit.setToolTipText("");

        lblcno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        edit2.setBackground(new java.awt.Color(0, 204, 0));
        edit2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        edit2.setText("EDIT");
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });

        textcnoedit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lbldesig.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbldesig.setPreferredSize(new java.awt.Dimension(0, 21));

        edit3.setBackground(new java.awt.Color(0, 204, 0));
        edit3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        edit3.setText("EDIT");
        edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit3ActionPerformed(evt);
            }
        });

        textdesigedit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblqualify.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        edit4.setBackground(new java.awt.Color(0, 204, 0));
        edit4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        edit4.setText("EDIT");
        edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit4ActionPerformed(evt);
            }
        });

        textqualifyedit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btcheck.setBackground(new java.awt.Color(0, 153, 153));
        btcheck.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btcheck.setText("CHECK MEMBER");
        btcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcheckActionPerformed(evt);
            }
        });

        lblid.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblid.setText(" Your Admin Id");

        textadmid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblpass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblpass.setText(" Password");

        textpass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btupdate.setBackground(new java.awt.Color(51, 204, 0));
        btupdate.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btupdate.setText("UPDATE");
        btupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btupdateActionPerformed(evt);
            }
        });

        btclear.setBackground(new java.awt.Color(255, 255, 0));
        btclear.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btclear.setText("RESET");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        btback.setBackground(new java.awt.Color(204, 51, 0));
        btback.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btback)
                        .addGap(48, 48, 48)
                        .addComponent(btclear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textmemid, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(textcnoedit, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                    .addComponent(edit2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblqualify, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textdesigedit, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbldesig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblcno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textnameedit, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblid)
                                                .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textadmid)
                                                .addComponent(textpass, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                            .addGap(60, 60, 60))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(textqualifyedit)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(edit1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(edit3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(edit4, javax.swing.GroupLayout.Alignment.TRAILING)))))))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btupdate)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textmemid, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btback)
                    .addComponent(btclear)
                    .addComponent(btcheck))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textnameedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblcno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textcnoedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldesig, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textdesigedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblqualify, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textqualifyedit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textadmid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpass)
                    .addComponent(textpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btupdate)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcheckActionPerformed
        mem_id=textmemid.getText().trim();
        if(mem_id.isEmpty()){
            lblname.setVisible(true);
            lblname.setText("Enter Member Admin Id");
            return;
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="Select adm_name,acno,desig,qualify from admin where adm_id=?";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,mem_id);
            ResultSet rs=ps.executeQuery();
            if (rs.next()) {
                lblname.setVisible(true);
                lblcno.setVisible(true);
                lbldesig.setVisible(true);
                lblqualify.setVisible(true);    
                edit1.setVisible(true);
                edit2.setVisible(true);
                edit3.setVisible(true);
                edit4.setVisible(true);
                lblname.setText("Employee Name: " + rs.getString("adm_name"));
                lblcno.setText("Phone: " + rs.getString("acno"));
                lbldesig.setText("Designation: " + rs.getString("desig"));       
                lblqualify.setText("Qualification: " + rs.getString("qualify"));
                
                
            } 
            else {
                lblname.setVisible(true);
                lblname.setText("No record found!");
            }
            
        }
        catch(Exception e){
              System.out.println(e);
        }
    }//GEN-LAST:event_btcheckActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        
        textnameedit.setVisible(true);
        if(edit==false){
            btupdate.setVisible(true);
            lblid.setVisible(true);
            lblpass.setVisible(true);
            textadmid.setVisible(true);
            textpass.setVisible(true);
            edit=true;
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_edit1ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        
        textcnoedit.setVisible(true);
        if(edit==false){
            btupdate.setVisible(true);
            lblid.setVisible(true);
            lblpass.setVisible(true);
            textadmid.setVisible(true);
            textpass.setVisible(true);
            edit=true;
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_edit2ActionPerformed

    private void edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit3ActionPerformed
        textdesigedit.setVisible(true);
        if(edit==false){
            btupdate.setVisible(true);
            lblid.setVisible(true);
            lblpass.setVisible(true);
            textadmid.setVisible(true);
            textpass.setVisible(true);
            edit=true;
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_edit3ActionPerformed

    private void edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit4ActionPerformed
        textqualifyedit.setVisible(true);
        if(edit==false){
            btupdate.setVisible(true);
            lblid.setVisible(true);
            lblpass.setVisible(true);
            textadmid.setVisible(true);
            textpass.setVisible(true);
            edit=true;
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_edit4ActionPerformed

    private void textmemidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textmemidKeyTyped
        lblname.setText("");
        lblname.setVisible(false);
        
    }//GEN-LAST:event_textmemidKeyTyped

    private void textmemidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textmemidKeyPressed
        lblname.setText("");
        lblname.setVisible(false);
    }//GEN-LAST:event_textmemidKeyPressed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        textmemid.setText("");
        lblname.setText("");
        lblcno.setText("");
        lbldesig.setText("");
        lblqualify.setText("");
        textnameedit.setText("");
        textcnoedit.setText("");
        textdesigedit.setText("");
        textqualifyedit.setText("");
        textadmid.setText("");
        textpass.setText("");
        textnameedit.setVisible(false);
        textcnoedit.setVisible(false);
        textdesigedit.setVisible(false);
        textqualifyedit.setVisible(false);
        textadmid.setVisible(false);
        textpass.setVisible(false);
        lblpass.setVisible(false);
        lblid.setVisible(false);
        edit1.setVisible(false);
        edit2.setVisible(false);
        edit3.setVisible(false);
        edit4.setVisible(false);
        btupdate.setVisible(false);
        edit=false;
    }//GEN-LAST:event_btclearActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        new Adminheadhomeframe().setVisible(true);
    }//GEN-LAST:event_btbackActionPerformed

    private void btupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btupdateActionPerformed
        if (textnameedit.getText().trim().isEmpty()){
            fullname=lblname.getText();
            editname=fullname.substring(fullname.indexOf(":")+1).trim();
            
        }
        else{
            editname=textnameedit.getText();
        }
        if (textcnoedit.getText().trim().isEmpty()){
            fullcno=lblcno.getText();
            editcno=fullcno.substring(fullcno.indexOf(":")+1).trim();
            
        }
        else{
            editcno=textcnoedit.getText();
        }
        if (textdesigedit.getText().trim().isEmpty()){
            fulldesig=lbldesig.getText();
            editdesig=fulldesig.substring(fulldesig.indexOf(":")+1).trim();
            
        }
        else{
            editdesig=textdesigedit.getText();
        }
        if (textqualifyedit.getText().trim().isEmpty()){
            fullqualify=lblqualify.getText();
            editqualify=fullqualify.substring(fullqualify.indexOf(":")+1).trim();
           
        }
        else{
            editqualify=textqualifyedit.getText();
        }
        String admid=textadmid.getText().trim();
        String admpass=textpass.getText().trim();
        if(admid.isEmpty()){
            textadmid.setText("FILL !!!");
            return;
        }
        if(admpass.isEmpty()){
            textpass.setText("FILL !!!");
            return;
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="Select * from admin where adm_id=? and adm_password=? and desig='Head Admin'";          
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,admid);
            ps.setString(2,admpass);
            ResultSet rs=ps.executeQuery();
            if (rs.next()) {
                String qry1="update admin set adm_name=?,acno=?,desig=?,qualify=?  where adm_id=?";
                PreparedStatement ps1=con.prepareStatement(qry1);
                ps1.setString(1,editname);
                ps1.setString(2,editcno);
                ps1.setString(3,editdesig);
                ps1.setString(4,editqualify);
                ps1.setString(5,mem_id);
                int a=ps1.executeUpdate();
                if (a==1){
                    String qry2="Select adm_name,acno,desig,qualify from admin where adm_id=?";
                    PreparedStatement ps2=con.prepareStatement(qry2);
                    ps2.setString(1,mem_id);
                    ResultSet rs2=ps2.executeQuery();
                    if (rs2.next()) {
                        lblname.setVisible(true);
                        lblcno.setVisible(true);
                        lbldesig.setVisible(true);
                        lblqualify.setVisible(true);    
                        edit1.setVisible(false);
                        edit2.setVisible(false);
                        edit3.setVisible(false);
                        edit4.setVisible(false);
                        lblname.setText("Employee Name: " + rs2.getString("adm_name"));
                        lblcno.setText("Phone: " + rs2.getString("acno"));
                        lbldesig.setText("Designation: " + rs2.getString("desig"));       
                        lblqualify.setText("Qualification: " + rs2.getString("qualify"));
                        textnameedit.setVisible(false);
                        textcnoedit.setVisible(false);
                        textdesigedit.setVisible(false);
                        textqualifyedit.setVisible(false);
                        textadmid.setVisible(false);
                        textpass.setVisible(false);
                        btupdate.setVisible(false);
                        lblid.setVisible(false);
                        lblpass.setVisible(false);
                    }
                    else{
                        lblname.setVisible(true);
                        lblcno.setVisible(false);
                        lbldesig.setVisible(false);
                        lblqualify.setVisible(false);    
                        edit1.setVisible(false);
                        edit2.setVisible(false);
                        edit3.setVisible(false);
                        edit4.setVisible(false);
                        textnameedit.setVisible(false);
                        textcnoedit.setVisible(false);
                        textdesigedit.setVisible(false);
                        textqualifyedit.setVisible(false);
                        textadmid.setVisible(false);
                        textpass.setVisible(false);
                        btupdate.setVisible(false);
                        lblid.setVisible(false);
                        lblpass.setVisible(false);
                        lblname.setText("Updation Failled !!!");
                    }
                }   
            } 
            else {
                lblname.setVisible(true);
                lblname.setText("UnAuthorization detected");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btupdateActionPerformed
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateadminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateadminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateadminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateadminframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateadminframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btcheck;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btupdate;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcno;
    private javax.swing.JLabel lbldesig;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblqualify;
    private javax.swing.JTextField textadmid;
    private javax.swing.JTextField textcnoedit;
    private javax.swing.JTextField textdesigedit;
    private javax.swing.JTextField textmemid;
    private javax.swing.JTextField textnameedit;
    private javax.swing.JTextField textpass;
    private javax.swing.JTextField textqualifyedit;
    // End of variables declaration//GEN-END:variables
}
