
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Viewpasswordframe extends javax.swing.JFrame {
    String mem_name,adm_name,type,admid,memid,password;
    /**
     * Creates new form Viewpasswordframe
     */
    public Viewpasswordframe() {
        initComponents();
        lblheadpass.setVisible(false);
        lblmess.setVisible(false);
        lblpass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbtype = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textadminid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textadminpassword = new javax.swing.JTextField();
        lblmess = new javax.swing.JLabel();
        chkfirst = new javax.swing.JCheckBox();
        chksecod = new javax.swing.JCheckBox();
        btback = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        btview = new javax.swing.JButton();
        lblheadpass = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 228, 184));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 750));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("VIEW PASSWORD !!!");

        cmbtype.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEMBER", "Employee", "Service Partner", "Admin" }));
        cmbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Select Member Type");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Enter Member Id");

        textid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textidKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Enter Your Head Admin Id");

        textadminid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textadminid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textadminidKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Enter Password");

        textadminpassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        textadminpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textadminpasswordKeyTyped(evt);
            }
        });

        lblmess.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        chkfirst.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkfirst.setText("I confirm that I am authorized to view this password and agree to use it responsibly.");

        chksecod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chksecod.setText(" I am aware that this action will be recorded and accept the consequences of misuse.");

        btback.setBackground(new java.awt.Color(204, 0, 0));
        btback.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btback.setText("BACK");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btclear.setBackground(new java.awt.Color(255, 255, 0));
        btclear.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        btview.setBackground(new java.awt.Color(0, 255, 0));
        btview.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btview.setText("VIEW");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });

        lblheadpass.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblheadpass.setText("PASSWORD -:");

        lblpass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblheadpass, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chksecod)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btback)
                                .addGap(121, 121, 121)
                                .addComponent(btclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btview))
                            .addComponent(chkfirst, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(lblmess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textid)
                                    .addComponent(cmbtype, 0, 254, Short.MAX_VALUE)
                                    .addComponent(textadminid)
                                    .addComponent(textadminpassword)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbtype))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textadminid))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textadminpassword))
                .addGap(35, 35, 35)
                .addComponent(lblmess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(chkfirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chksecod)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btback)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btclear)
                        .addComponent(btview)))
                .addGap(49, 49, 49)
                .addComponent(lblheadpass)
                .addGap(18, 18, 18)
                .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        type= cmbtype.getSelectedItem().toString().trim();
        memid=textid.getText().trim();
        admid=textadminid.getText().trim();
        password=textadminpassword.getText().trim();
        if(type.equals("MEMBER")){
            lblmess.setVisible(true);
            lblmess.setText("Pls Select Member Type");
            return;
        }
        if(memid.isEmpty()){
            lblmess.setVisible(true);
            lblmess.setText("Pls Enter Member Id");
            return;
        }
        if(admid.isEmpty()){
            lblmess.setVisible(true);
            lblmess.setText("Pls Enter Your Admin Id");
            return;
        }
        if(password.isEmpty()){
            lblmess.setVisible(true);
            lblmess.setText("Pls Enter Your Id's Password");
            return;
        }
        if (!chkfirst.isSelected() || !chksecod.isSelected()) {
            lblmess.setVisible(true);
            lblmess.setText("Please check all the confirmation boxes");
            return;
        }
        System.out.println(type);
        try{
            Class.forName("com.mysql.jdbc.Driver");
	    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/homesupport?user=root&password=satyam");
            String qry="Select * from admin where adm_id=? and adm_password=? and desig='Head Admin'";
            PreparedStatement ps=con.prepareStatement(qry);
            ps.setString(1,admid);
            ps.setString(2,password);
            ResultSet rs=ps.executeQuery();
            if (rs.next()){
                 adm_name=rs.getString("adm_name");
                if(type.equals("Employee")){
                    String qry1="Select emp_password,emp_name from employee where emp_id=? ";
                    PreparedStatement ps1=con.prepareStatement(qry1);
                    ps1.setString(1,memid);

                    ResultSet rs1=ps1.executeQuery();
                    if (rs1.next()){
                        mem_name=rs1.getString("emp_name");
                        System.out.println(mem_name);
                        lblheadpass.setVisible(true);
                        lblpass.setVisible(true);
                        lblpass.setText(rs1.getString("emp_password"));
                    }
                    else{
                        lblmess.setVisible(true);
                       lblmess.setText("Employee Not Found");
                    }
                }
                else if(type.equals("Service Partner")){
                    String qry2="Select sp_pass,sp_name from partner where sp_id=? ";
                    PreparedStatement ps2=con.prepareStatement(qry2);
                    ps2.setString(1,memid);

                    ResultSet rs2=ps2.executeQuery();
                    if (rs2.next()){
                         mem_name=rs2.getString("sp_name");
                        System.out.println(mem_name);
                        lblheadpass.setVisible(true);
                        lblpass.setVisible(true);
                        lblpass.setText(rs2.getString("sp_pass"));
                    }
                    else{
                        lblmess.setVisible(true);
                       lblmess.setText("Partner Not Found");
                    }
                }
                else if(type.equals("Admin")){
                    String qry3="Select adm_password,adm_name from admin where adm_id=? ";
                    PreparedStatement ps3=con.prepareStatement(qry3);
                    ps3.setString(1,memid);
                    ResultSet rs3=ps3.executeQuery();
                    if (rs3.next()){
                         mem_name=rs3.getString("adm_name");
                        System.out.println(mem_name);
                        lblheadpass.setVisible(true);
                        lblpass.setVisible(true);
                        lblpass.setText(rs3.getString("adm_password"));
                    }
                    else{
                        lblmess.setVisible(true);
                        lblmess.setText("Admin Not Found");
                    }   
                } 
                String qry4="insert into viewpassword(mem_type,mem_id,mem_name,hadmin_id,hadmin_name,undertake) values (?,?,?,?,?,?)";
                    PreparedStatement ps4= con.prepareStatement(qry4);
                    ps4.setString(1,type);
                    ps4.setString(2,memid);
                    ps4.setString(3,mem_name);
                    ps4.setString(4,admid);
                    ps4.setString(5,adm_name);
                    ps4.setString(6,"Confirmed");
                    ps4.executeUpdate();
                    
            }
            else{
                lblmess.setVisible(true);
                lblmess.setText("Unauthoriation !! Invalid Id/Password ");
            }
            
        }    
        catch(Exception e){
            System.out.println(e);
        }
         
        
    }//GEN-LAST:event_btviewActionPerformed

    private void cmbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtypeActionPerformed
        lblmess.setVisible(false);
        lblmess.setText("");
        lblheadpass.setVisible(false);
        lblpass.setVisible(false);
        lblmess.setText("");
    }//GEN-LAST:event_cmbtypeActionPerformed

    private void textidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textidKeyTyped
        lblmess.setVisible(false);
        lblmess.setText("");
        lblheadpass.setVisible(false);
        lblpass.setVisible(false);
        lblmess.setText("");
    }//GEN-LAST:event_textidKeyTyped

    private void textadminidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textadminidKeyTyped
        lblmess.setVisible(false);
        lblmess.setText("");
        lblheadpass.setVisible(false);
        lblpass.setVisible(false);
        lblmess.setText("");
    }//GEN-LAST:event_textadminidKeyTyped

    private void textadminpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textadminpasswordKeyTyped
        lblmess.setVisible(false);
        lblmess.setText("");
        lblheadpass.setVisible(false);
        lblpass.setVisible(false);
        lblmess.setText("");
    }//GEN-LAST:event_textadminpasswordKeyTyped

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        lblmess.setVisible(false);
        lblmess.setText("");
        lblheadpass.setVisible(false);
        lblpass.setVisible(false);
        lblmess.setText("");
        cmbtype.setSelectedIndex(0);
        textid.setText("");
        textadminid.setText("");
        textadminpassword.setText("");
        
    }//GEN-LAST:event_btclearActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        dispose();
        new Adminheadhomeframe().setVisible(true);
    }//GEN-LAST:event_btbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewpasswordframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewpasswordframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewpasswordframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewpasswordframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewpasswordframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btview;
    private javax.swing.JCheckBox chkfirst;
    private javax.swing.JCheckBox chksecod;
    private javax.swing.JComboBox<String> cmbtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblheadpass;
    private javax.swing.JLabel lblmess;
    private javax.swing.JLabel lblpass;
    private javax.swing.JTextField textadminid;
    private javax.swing.JTextField textadminpassword;
    private javax.swing.JTextField textid;
    // End of variables declaration//GEN-END:variables
}
